# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create(name: 'Jon', email: 'jon@gmail.com', password: 'jon123')
# User.create(name: 'Arya', email: 'arya@gmail.com', password: 'arya123')
# User.create(name: 'Sansa', email: 'sansa@gmail.com', password: 'sansa123')
# User.create(name: 'Bran', email: 'bran@gmail.com', password: 'bran123')
# User.create(name: 'Rob', email: 'rob@gmail.com', password: 'rob123')
# User.create(name: 'Rickon', email: 'rickon@gmail.com', password: 'rickon123')

# Roaster.create(name: 'Audun Coffee', country: 'Poland')
# Roaster.create(name: 'Cloud Picker', country: 'Irleand')
# Roaster.create(name: 'Five Elephant', country: 'Germany')
# Roaster.create(name: 'Hard Beans', country: 'Poland')
# Roaster.create(name: 'Hayb', country: 'Poland')
# Roaster.create(name: 'Java Coffee', country: 'Poland')
# Roaster.create(name: 'Populus Coffee', country: 'Germany')
# Roaster.create(name: 'Simplo', country: 'Poland')
# Roaster.create(name: 'Johan & Nystrom', country: 'Sweden')
# Roaster.create(name: 'Fjord', country: 'Germany')
# Roaster.create(name: 'Coffeelab', country: 'Poland')
# Roaster.create(name: 'Etno Cafe', country: 'Poland')
# Roaster.create(name: 'Lavazza', country: 'Italy')
# Roaster.create(name: 'Rocket Bean', country: 'Latvia')
# Roaster.create(name: 'Solberg & Hansen', country: 'Norway')

# Bean.create(name: 'Salwador El Martillo Espresso', method: 'Natural', country: 'Salwador', roast: 'medium', description: 'Varietal: Bourbon, Catuai', roaster_id: 1)
# Bean.create(name: 'Etiopia Boji', method: 'Washed', country: 'Ethiopia', roast: 'light', description: 'Varietal: Heirloom', roaster_id: 1)
# Bean.create(name: 'Kenya Muchagara PB Filter', method: 'Washed', country: 'Kenya', roast: 'light', description: 'Varietal: SL28, SL34, Ruiru 11', roaster_id: 2)
# Bean.create(name: 'Colombia Inga Aponte Espresso', method: 'Washed', country: 'Colombia', roast: 'medium', description: 'Varietal: Caturra, Altitude: 1850 - 2250 m n.p.m.', roaster_id: 2)
# Bean.create(name: 'Burundi Buziraguhindwa Shade Dried Filter', method: 'Washed', country: 'Washed', roast: 'light', description: 'Varietal: Red Bourbon', roaster_id: 3)
# Bean.create(name: 'Ethiopia Mokanesa Bulga Filter', method: 'Washed', country: 'Ethiopia', roast: 'light', description: 'Varietal: Heirloom', roaster_id: 3)
# Bean.create(name: 'Burundi Gaharo 55', method: 'Washed', country: 'Burundi', roast: 'light', description: 'Varietal: Red Bourbon', roaster_id: 4)
# Bean.create(name: 'Kolumbia Manuel Alberto Gongora', method: 'Washed', country: 'Colombia', roast: 'light', description: 'Varietal: Castillo', roaster_id: 4)
# Bean.create(name: 'Peru El Diamante', method: 'Washed', country: 'Peru', roast: 'light', description: 'Varietal: Caturra', roaster_id: 5)
# Bean.create(name: 'Ethiopia Mokanesa Bulga', method: 'Washed', country: 'Ethipoia', roast: 'light', description: 'Varietal: Mixed heirloom', roaster_id: 5)
# Bean.create(name: 'Burundi Bwayi', method: 'Washed', country: 'Burundi', roast: 'light', description: 'Varietal: Bourbon, Jackson, Mibirizi', roaster_id: 6)
# Bean.create(name: 'Brazil Fazenda Sertao Omniroast', method: 'Natural', country: 'Brazil', roast: 'medium', description: 'Varietal: Yellow Catuai', roaster_id: 7)
# Bean.create(name: 'Costa Rica Genesis Omniroast', method: 'Red Honey', country: 'Cost Rica', roast: 'medium', description: 'Varietal: Villa Lobos', roaster_id: 7)
# Bean.create(name: 'Kenia Limelight Filter', method: 'Washed', country: 'Kenya', roast: 'light', description: 'Varietal: SL28, SL34', roaster_id: 8)
# Bean.create(name: 'Rwanda Life on Mars? Filter', method: 'Natural', country: 'Rwanda', roast: 'light', description: 'Varietal: Red Bourbon', roaster_id: 8)
# Bean.create(name: 'Ethiopia Guji', method: 'Natural', country: 'Ethiopia', roast: 'light', description: 'Varietal: Mixed Heirloom', roaster_id: 9)
# Bean.create(name: 'Ethiopia Welena', method: 'Washed', country: 'Ethiopia', roast: 'light', description: 'Varietal: Mixed Heirloom', roaster_id: 9)
# Bean.create(name: 'Kenya Kii Filter', method: 'Washed', country: 'Kenya', roast: 'light', description: 'Varietal: SL28, SL34, K7', roaster_id: 10)
# Bean.create(name: 'Ethiopia Duromina Filter', method: 'Washed', country: 'Ethiopia', roast: 'light', description: 'Varietal: Heirloom', roaster_id: 10)
# Bean.create(name: 'Kolumbia Pitalito Decaf', method: 'Washed', country: 'Colombia', roast: 'light', description: 'Varietal: Castillo, Caturra, Colombia', roaster_id: 11)
# Bean.create(name: 'Honduras Norma Iris Fiallos Espresso', method: 'Natural', country: 'Honduras', roast: 'medium', description: 'Varietal: Red Catuai', roaster_id: 11)
# Bean.create(name: 'Etiopia Yirgacheffe', method: 'Washed', country: 'Ethiopia', roast: 'medium', description: 'Varietal: Heirloom', roaster_id: 12)
# Bean.create(name: 'Colombia Medellin', method: 'Washed', country: 'Colombia', roast: 'medium', description: 'Varietal: Heirloom', roaster_id: 12)
# Bean.create(name: 'Sweet Dream Peru Chanchamayo El Mango Espresso', method: 'Washed', country: 'Peru', roast: 'medium', description: 'Varietal: Catimor, caturra, typica, pache', roaster_id: 14)
# Bean.create(name: 'Colombia Huila Palestina Finca Cuatro Vientos', method: 'Washed', country: 'Colombia', roast: 'light', description: 'Varietal: Pink Bourbon', roaster_id: 14)
# Bean.create(name: 'Nicaragua Mama Mina', method: 'Washed', country: 'Nicaragua', roast: 'light', description: 'Varietal: Pacamara', roaster_id: 15)
# Bean.create(name: 'Ethiopia Black Espresso Vol. 4', method: 'Natural', country: 'Ethiopia', roast: 'light', description: 'Varietal: Heirloom', roaster_id: 15)


# Recipe.create(roaster_id: 1, bean_id: 1, temperature: 90, water: 500, dose: 30, time: '2000-01-01 03:15:00', method: 'V60', description: 'Yummy', grinder: 'Hario', clicks: 15, user_id: 1, rate:4 )
# Recipe.create(roaster_id: 2, bean_id: 3, temperature: 91, water: 500, dose: 30, time: '2000-01-01 03:15:00', method: 'Aeropress', description: 'Yummy', grinder: 'Hario', clicks: 15, user_id: 2, rate: 4)
# Recipe.create(roaster_id: 3, bean_id: 5, temperature: 92, water: 500, dose: 30, time: '2000-01-01 03:15:00', method: 'Chemex', description: 'Yummy', grinder: 'Xeleo', clicks:17 , user_id: 3, rate:2 )
# Recipe.create(roaster_id: 4, bean_id: 7, temperature: 97, water: 500, dose: 30, time: '2000-01-01 03:15:00', method: 'V60', description: 'Yummy', grinder: 'Comandante', clicks: 22, user_id: 4, rate: 4)
# Recipe.create(roaster_id: 5, bean_id: 9, temperature: 93, water: 500, dose: 30, time: '2000-01-01 03:15:00', method: 'Chemex', description: 'Yummy', grinder: 'Hario', clicks: 13, user_id: 5, rate:4 )
# Recipe.create(roaster_id: 6, bean_id: 11, temperature: 94, water: 500, dose: 30, time: '2000-01-01 03:15:00', method: 'Aeropress', description: 'Yummy', grinder: 'Xeleo', clicks: 12, user_id: 6, rate: 5)
# Recipe.create(roaster_id: 7, bean_id: 12, temperature: 93, water: 500, dose: 30, time: '2000-01-01 03:15:00', method: 'V60', description: 'Yummy', grinder: 'Xeleo', clicks: 19, user_id: 1, rate: 3)
# Recipe.create(roaster_id: 8, bean_id: 14, temperature: 92, water: 500, dose: 30, time: '2000-01-01 03:15:00', method: 'V60', description: 'Yummy', grinder: 'Hario', clicks: 17, user_id: 2, rate: 2)